# 🪙 Configuração de Financiamento e Patrocínio

# Insira o seu utilizador do GitHub Sponsors dentro dos parênteses retos:
github: [ismapereira]

# Caso utilize outras plataformas no futuro, basta remover o '#' e preencher:
# patreon: seu_utilizador
# buy_me_a_coffee: seu_utilizador
# custom: ['https://link-para-seu-pix-ou-apoio-customizado']
